# Generated by Django 6.0.3 on 2026-05-20 10:21

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Texto introductorio de la sección noticias')),
            ],
            options={
                'verbose_name': 'Página de noticias',
                'verbose_name_plural': 'Páginas de noticias',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title', 'label': 'Título'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Párrafo'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Imagen'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'icon': 'openquote', 'label': 'Cita'})}, verbose_name='Contenido')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen destacada')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
            bases=('wagtailcore.page',),
        ),
    ]
