# Generated by Django 6.0.3 on 2026-06-09 20:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectivePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Texto introductorio')),
                ('content', wagtail.fields.StreamField([('hero_image', 1), ('rich_text', 2), ('steps_list', 12), ('documents', 18), ('table', 20), ('tabs', 25), ('contact', 28), ('separator', 29)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen principal', 'required': True}), 1: ('wagtail.blocks.StructBlock', [[('image', 0)]], {}), 2: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Texto enriquecido'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Título del paso'}), 5: ('wagtail.blocks.RichTextBlock', (), {'label': 'Descripción'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Texto del enlace'}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 8: ('wagtail.blocks.StructBlock', [[('text', 6), ('url', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Enlaces', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('step_title', 4), ('description', 5), ('links', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Pasos'}), 12: ('wagtail.blocks.StructBlock', [[('title', 3), ('steps', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Título del documento'}), 15: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Archivo'}), 16: ('wagtail.blocks.StructBlock', [[('title', 14), ('file', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'label': 'Documentos'}), 18: ('wagtail.blocks.StructBlock', [[('title', 13), ('documents', 17)]], {}), 19: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Usa el editor para crear una tabla HTML', 'label': 'Contenido de la tabla'}), 20: ('wagtail.blocks.StructBlock', [[('content', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'Título de la pestaña'}), 22: ('wagtail.blocks.RichTextBlock', (), {'label': 'Contenido'}), 23: ('wagtail.blocks.StructBlock', [[('tab_title', 21), ('tab_content', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'label': 'Pestañas'}), 25: ('wagtail.blocks.StructBlock', [[('tabs', 24)]], {}), 26: ('wagtail.blocks.EmailBlock', (), {}), 27: ('wagtail.blocks.ListBlock', (26,), {'label': 'Correos electrónicos'}), 28: ('wagtail.blocks.StructBlock', [[('emails', 27)]], {}), 29: ('wagtail.blocks.StructBlock', [[]], {'icon': 'horizontalrule', 'label': 'Separador'})})),
            ],
            options={
                'verbose_name': 'Página de Ingresantes',
                'verbose_name_plural': 'Páginas de Ingresantes',
            },
            bases=('wagtailcore.page',),
        ),
    ]
