# Generated by Django 6.0.3 on 2026-06-09 16:49

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Texto introductorio')),
                ('content', wagtail.fields.StreamField([('rich_text', 0), ('link_cards', 6), ('document_list', 10), ('calendar', 14), ('image_gallery', 16), ('separator', 17)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Texto enriquecido'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Descripción', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'URL', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'bi bi-link', 'label': 'Clase del ícono (ej: bi bi-calendar)', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 1), ('description', 2), ('link_url', 3), ('icon_class', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'icon': 'th-large', 'label': 'Tarjetas de enlaces'}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Título del documento', 'required': True}), 8: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Archivo PDF/Word', 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('title', 7), ('document', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'icon': 'doc-full', 'label': 'Lista de documentos'}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'required': False}), 12: ('wagtail.blocks.URLBlock', (), {'label': 'URL del calendario (embed)', 'required': True}), 13: ('wagtail.blocks.IntegerBlock', (), {'default': 600, 'label': 'Altura en píxeles'}), 14: ('wagtail.blocks.StructBlock', [[('title', 11), ('embed_url', 12), ('height', 13)]], {}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 16: ('wagtail.blocks.ListBlock', (15,), {'icon': 'image', 'label': 'Galería de imágenes'}), 17: ('wagtail.blocks.StructBlock', [[]], {'icon': 'horizontalrule', 'label': 'Separador'})}, verbose_name='Contenido principal')),
            ],
            options={
                'verbose_name': 'Página de Docentes',
                'verbose_name_plural': 'Páginas de Docentes',
            },
            bases=('wagtailcore.page',),
        ),
    ]
