# Generated by Django 6.0.3 on 2026-05-20 10:21

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Texto introductorio')),
            ],
            options={
                'verbose_name': 'Página de carreras',
                'verbose_name_plural': 'Páginas de carreras',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CareerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('career_code', models.CharField(blank=True, max_length=20, verbose_name='Código de la carrera')),
                ('duration', models.CharField(blank=True, help_text='Ej: 5 años', max_length=100, verbose_name='Duración')),
                ('degree', models.CharField(blank=True, help_text='Ej: Ingeniero/a en Informática', max_length=200, verbose_name='Título otorgado')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('list', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title', 'label': 'Título'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Párrafo'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Imagen'}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.ListBlock', (3,), {'icon': 'list', 'label': 'Lista'})}, verbose_name='Contenido principal')),
                ('syllabus_plans', wagtail.fields.StreamField([('plan', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ej: 2003, 2010, 2024', 'label': 'Año', 'max_length': 10, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Opcional. Ej: 'Plan anterior', 'Plan vigente'", 'label': 'Título personalizado', 'max_length': 100, 'required': False}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Subir el plan de estudios en PDF', 'label': 'Archivo PDF', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('year', 0), ('title', 1), ('file', 2)]], {})}, help_text='Agrega uno o más planes de estudio con su año y PDF', verbose_name='Planes de Estudio')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('basic_contents_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Contenidos Básicos')),
                ('consultation_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Página de Consultas')),
                ('department_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Página del Departamento')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen principal')),
                ('graduate_profile_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Perfil del Egresado')),
                ('professional_profile_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Incumbencias Profesionales')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['order', 'title'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la asignatura')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Código')),
                ('workload', models.CharField(blank=True, max_length=100, verbose_name='Carga horaria')),
                ('syllabus_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Programa analítico (PDF)')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CareerSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Año en esta carrera')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_subjects', to='courses.careerpage')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_careers', to='courses.subject')),
            ],
            options={
                'verbose_name': 'Asignatura por carrera',
                'verbose_name_plural': 'Asignaturas por carrera',
                'unique_together': {('page', 'subject')},
            },
        ),
    ]
