# Generated by Django 6.0.3 on 2026-05-20 10:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoritiesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Texto introductorio')),
            ],
            options={
                'verbose_name': 'Página de autoridades',
                'verbose_name_plural': 'Páginas de autoridades',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('carousel_slides', wagtail.fields.StreamField([('slide', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen de fondo', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Título principal', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Subtítulo o descripción', 'max_length': 200, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Texto del botón', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Enlace del botón', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('subtitle', 2), ('button_text', 3), ('button_link', 4)]], {})}, help_text='Agrega los slides que quieras mostrar en el carrusel principal')),
                ('cards', wagtail.fields.StreamField([('card', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ejemplo: bi-pencil-square, bi-mortarboard, etc.', 'label': 'Icono (Bootstrap icon)', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Primera línea del título', 'max_length': 50, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Segunda línea del título', 'max_length': 50, 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Enlace', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('custom-grad-1', 'Gradiente 1'), ('custom-grad-2', 'Gradiente 2'), ('custom-grad-3', 'Gradiente 3'), ('custom-grad-4', 'Gradiente 4'), ('custom-grad-5', 'Gradiente 5'), ('custom-grad-6', 'Gradiente 6')], 'label': 'Color de la tarjeta'}), 5: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title_line1', 1), ('title_line2', 2), ('link', 3), ('gradient_class', 4)]], {})}, help_text='Agrega las tarjetas de acceso rápido')),
                ('institutional_section', wagtail.fields.StreamField([('institutional', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Institucional', 'label': 'Título de la sección', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Primer párrafo', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Segundo párrafo', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Conocer más', 'label': 'Texto del botón', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Enlace del botón', 'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen institucional', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('text_line1', 1), ('text_line2', 2), ('button_text', 3), ('button_link', 4), ('image', 5)]], {})}, help_text='Sección institucional')),
                ('metrics_section', wagtail.fields.StreamField([('metrics', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': '10', 'label': 'Número 1', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'carreras de grado', 'label': 'Etiqueta 1', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'default': '12', 'label': 'Número 2', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'carreras de posgrado', 'label': 'Etiqueta 2', 'required': True}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Texto descriptivo', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'INSCRIBIRSE', 'label': 'Texto del botón', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'Enlace del botón', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('metric1_number', 0), ('metric1_label', 1), ('metric2_number', 2), ('metric2_label', 3), ('description', 4), ('button_text', 5), ('button_link', 6)]], {})}, help_text='Sección de métricas')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('position', models.CharField(max_length=200, verbose_name='Cargo')),
                ('bio', wagtail.fields.RichTextField(blank=True, verbose_name='Breve reseña')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Autoridad',
                'verbose_name_plural': 'Autoridades',
                'ordering': ['order', 'name'],
            },
        ),
    ]
