# Generated by Django 6.0.3 on 2026-05-22 00:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoritySectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Descripción de la sección')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen representativa')),
            ],
            options={
                'verbose_name': 'Sección de autoridades',
                'verbose_name_plural': 'Secciones de autoridades',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='authority',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorities', to='home.authoritysectionpage', verbose_name='Sección a la que pertenece'),
        ),
    ]
