# Generated by Django 6.0.3 on 2026-05-25 12:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_authoritysectionpage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoritysectionpage',
            name='sections',
            field=wagtail.fields.StreamField([('authority_section', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título de la sección', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Descripción introductoria', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('cards', 'Tarjetas (foto, nombre, cargo, bio)'), ('list', 'Lista simple (nombre, cargo)'), ('grid_cards', 'Tarjetas en cuadrícula'), ('horizontal_cards', 'Tarjetas horizontales')], 'label': 'Estilo de visualización'}), 3: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Authority',), {'label': 'Autoridad'}), 4: ('wagtail.blocks.BooleanBlock', (), {'label': 'Destacar', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('authority', 3), ('highlight', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Selecciona las autoridades que pertenecen a esta sección', 'label': 'Autoridades'}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('display_style', 2), ('authorities', 6)]], {})}, verbose_name='Secciones'),
        ),
    ]
