# Generated by Django 6.0.3 on 2026-05-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_authoritysectionpage_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authority',
            options={'ordering': ['name'], 'verbose_name': 'Autoridad', 'verbose_name_plural': 'Autoridades'},
        ),
        migrations.RemoveField(
            model_name='authority',
            name='order',
        ),
    ]
