# Generated by Django 6.0.3 on 2026-05-26 09:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_authoritysectionpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoritysectionpage',
            name='sections',
            field=wagtail.fields.StreamField([('authority_section', 7), ('collegiate_body', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título de la sección', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Descripción introductoria', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('cards', 'Tarjetas (foto, nombre, cargo, bio)'), ('list', 'Lista simple (nombre, cargo)'), ('grid_cards', 'Tarjetas en cuadrícula'), ('horizontal_cards', 'Tarjetas horizontales')], 'label': 'Estilo de visualización'}), 3: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Authority',), {'label': 'Autoridad'}), 4: ('wagtail.blocks.BooleanBlock', (), {'label': 'Destacar', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('authority', 3), ('highlight', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Selecciona las autoridades que pertenecen a esta sección', 'label': 'Autoridades'}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('display_style', 2), ('authorities', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'required': True}), 9: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Authority',), {'label': 'Titular'}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Docentes - Titulares'}), 11: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Authority',), {'label': 'Suplente'}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Docentes - Suplentes'}), 13: ('wagtail.blocks.ListBlock', (9,), {'label': 'Estudiantes - Titulares', 'required': False}), 14: ('wagtail.blocks.ListBlock', (11,), {'label': 'Estudiantes - Suplentes', 'required': False}), 15: ('wagtail.blocks.ListBlock', (9,), {'label': 'No docente - Titular', 'required': False}), 16: ('wagtail.blocks.ListBlock', (11,), {'label': 'No docente - Suplente', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 8), ('faculty_titular', 10), ('faculty_suplente', 12), ('student_titular', 13), ('student_suplente', 14), ('graduate_titular', 15), ('graduate_suplente', 16)]], {})}, verbose_name='Secciones'),
        ),
    ]
