# Generated by Django 6.0.3 on 2026-06-09 17:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cards',
            field=wagtail.fields.StreamField([('card', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ejemplo: bi-pencil-square, bi-mortarboard, etc.', 'label': 'Icono (Bootstrap icon)', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Primera línea del título', 'max_length': 50, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Segunda línea del título', 'max_length': 50, 'required': True}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Página interna de destino', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Enlace externo', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('custom-grad-1', 'Gradiente 1'), ('custom-grad-2', 'Gradiente 2'), ('custom-grad-3', 'Gradiente 3'), ('custom-grad-4', 'Gradiente 4'), ('custom-grad-5', 'Gradiente 5'), ('custom-grad-6', 'Gradiente 6')], 'label': 'Color de la tarjeta'}), 6: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title_line1', 1), ('title_line2', 2), ('link_page', 3), ('external_link', 4), ('gradient_class', 5)]], {})}, help_text='Agregá las tarjetas de acceso rápido'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='carousel_slides',
            field=wagtail.fields.StreamField([('slide', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen de fondo', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Título principal', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Subtítulo o descripción', 'max_length': 200, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Texto del botón', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Enlace del botón', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('subtitle', 2), ('button_text', 3), ('button_link', 4)]], {})}, help_text='Agregá los slides que quieras mostrar en el carrusel principal'),
        ),
    ]
