# Generated by Django 6.0.3 on 2026-06-11 13:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepage_cards_alter_homepage_carousel_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cards',
            field=wagtail.fields.StreamField([('card', 7)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bi', 'Bootstrap Icons'), ('fas', 'Font Awesome Solid'), ('far', 'Font Awesome Regular'), ('fab', 'Font Awesome Brands')], 'label': 'Familia de iconos'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ej: bi-mortarboard (Bootstrap) o fa-graduation-cap (Font Awesome)', 'label': 'Nombre del icono', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Primera línea del título', 'max_length': 50, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Segunda línea del título', 'max_length': 50, 'required': True}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Página interna de destino', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'Enlace externo', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('custom-grad-1', 'Gradiente 1'), ('custom-grad-2', 'Gradiente 2'), ('custom-grad-3', 'Gradiente 3'), ('custom-grad-4', 'Gradiente 4'), ('custom-grad-5', 'Gradiente 5'), ('custom-grad-6', 'Gradiente 6')], 'label': 'Color de la tarjeta'}), 7: ('wagtail.blocks.StructBlock', [[('icon_family', 0), ('icon', 1), ('title_line1', 2), ('title_line2', 3), ('link_page', 4), ('external_link', 5), ('gradient_class', 6)]], {})}, help_text='Agregá las tarjetas de acceso rápido'),
        ),
    ]
