# Generated by Django 6.0.3 on 2026-06-11 14:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cards',
            field=wagtail.fields.StreamField([('card', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ejemplo: bi-pencil-square, bi-mortarboard, etc.', 'label': 'Icono (Bootstrap icon)', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Primera línea del título', 'max_length': 50, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Segunda línea del título', 'max_length': 50, 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Enlace', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('custom-grad-1', 'Gradiente 1'), ('custom-grad-2', 'Gradiente 2'), ('custom-grad-3', 'Gradiente 3'), ('custom-grad-4', 'Gradiente 4'), ('custom-grad-5', 'Gradiente 5'), ('custom-grad-6', 'Gradiente 6')], 'label': 'Color de la tarjeta'}), 5: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title_line1', 1), ('title_line2', 2), ('link', 3), ('gradient_class', 4)]], {})}, help_text='Agregá las tarjetas de acceso rápido'),
        ),
    ]
