# Generated by Django 6.0.3 on 2026-05-20 10:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('contacto_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('content', wagtail.fields.StreamField([('hero_info', 3), ('rich_text', 4), ('links_group', 11), ('document_list', 17), ('news_list', 20), ('image_gallery', 22), ('quote', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título de sección', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Descripción principal', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen lateral o de fondo', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Texto enriquecido'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Título del grupo (opcional)', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Texto del enlace', 'required': True}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'URL', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'bi bi-link', 'label': 'Clase CSS del ícono (ej: bi bi-file-pdf)', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('link_text', 6), ('link_url', 7), ('icon_class', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Lista de enlaces'}), 11: ('wagtail.blocks.StructBlock', [[('group_title', 5), ('links', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Documentos útiles', 'label': 'Título'}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Título del documento'}), 14: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Archivo'}), 15: ('wagtail.blocks.StructBlock', [[('title', 13), ('document', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'label': 'Documentos'}), 17: ('wagtail.blocks.StructBlock', [[('title', 12), ('documents', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Novedades', 'label': 'Título de la sección'}), 19: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'label': 'Cantidad de novedades a mostrar', 'max_value': 10, 'min_value': 1}), 20: ('wagtail.blocks.StructBlock', [[('title', 18), ('max_items', 19)]], {}), 21: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 22: ('wagtail.blocks.ListBlock', (21,), {'icon': 'image', 'label': 'Galería de imágenes'}), 23: ('wagtail.blocks.BlockQuoteBlock', (), {'icon': 'openquote', 'label': 'Cita'})}, verbose_name='Contenido de la página')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DepartmentsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Texto de introducción para la página de departamentos.', null=True)),
            ],
            options={
                'verbose_name': 'Página de Índice de Departamentos',
                'verbose_name_plural': 'Páginas de Índice de Departamentos',
            },
            bases=('wagtailcore.page',),
        ),
    ]
